# Generated by Django 3.1.3 on 2021-01-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210110_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.transactiontype')),
            ],
        ),
    ]
